(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function q(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.g=g;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ea(a){return a.raw=a}function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var fa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};q("Object.assign",function(a){return a||fa});
var ja="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ka;if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var ma={a:!0},na={};try{na.__proto__=ma;la=na.a;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var oa=ka;
function v(a,b){a.prototype=ja(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.J=b.prototype}function pa(){this.j=!1;this.g=null;this.l=void 0;this.h=1;this.s=0;this.i=null}function qa(a){if(a.j)throw new TypeError("Generator is already running");a.j=!0}pa.prototype.m=function(a){this.l=a};function ra(a,b){a.i={pa:b,wa:!0};a.h=a.s}
pa.prototype.return=function(a){this.i={return:a};this.h=this.s};function sa(a){this.g=new pa;this.h=a}function ta(a,b){qa(a.g);var c=a.g.g;if(c)return ua(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return va(a)}
function ua(a,b,c,d){try{var e=b.call(a.g.g,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.j=!1,e;var g=e.value}catch(f){return a.g.g=null,ra(a.g,f),va(a)}a.g.g=null;d.call(a.g,g);return va(a)}function va(a){for(;a.g.h;)try{var b=a.h(a.g);if(b)return a.g.j=!1,{value:b.value,done:!1}}catch(c){a.g.l=void 0,ra(a.g,c)}a.g.j=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.wa)throw b.pa;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function wa(a){this.next=function(b){qa(a.g);a.g.g?b=ua(a,a.g.g.next,b,a.g.m):(a.g.m(b),b=va(a));return b};this.throw=function(b){qa(a.g);a.g.g?b=ua(a,a.g.g["throw"],b,a.g.m):(ra(a.g,b),b=va(a));return b};this.return=function(b){return ta(a,b)};this[Symbol.iterator]=function(){return this}}function xa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})}
function ya(a){return xa(new wa(new sa(a)))}function za(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
q("Promise",function(a){function b(f){this.g=0;this.i=void 0;this.h=[];this.s=!1;var h=this.j();try{f(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(h){h(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(f)};var e=p.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var h=0;h<f.length;++h){var k=
f[h];f[h]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:f(this.D),reject:f(this.l)}};b.prototype.D=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.K(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.C(f):this.m(f)}};
b.prototype.C=function(f){var h=void 0;try{h=f.then}catch(k){this.l(k);return}"function"==typeof h?this.L(h,f):this.m(f)};b.prototype.l=function(f){this.u(2,f)};b.prototype.m=function(f){this.u(1,f)};b.prototype.u=function(f,h){if(0!=this.g)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.g);this.g=f;this.i=h;2===this.g&&this.I();this.v()};b.prototype.I=function(){var f=this;e(function(){if(f.B()){var h=p.console;"undefined"!==typeof h&&h.error(f.i)}},1)};b.prototype.B=
function(){if(this.s)return!1;var f=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof h?f=new h("unhandledrejection",{cancelable:!0}):(f=p.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.v=function(){if(null!=this.h){for(var f=0;f<this.h.length;++f)g.h(this.h[f]);this.h=null}};var g=new c;b.prototype.K=
function(f){var h=this.j();f.R(h.resolve,h.reject)};b.prototype.L=function(f,h){var k=this.j();try{f.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,h){function k(z,D){return"function"==typeof z?function(ha){try{l(z(ha))}catch(ia){m(ia)}}:D}var l,m,t=new b(function(z,D){l=z;m=D});this.R(k(f,l),k(h,m));return t};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.R=function(f,h){function k(){switch(l.g){case 1:f(l.i);break;case 2:h(l.i);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;null==this.h?g.h(k):this.h.push(k);this.s=!0};b.resolve=d;b.reject=function(f){return new b(function(h,k){k(f)})};b.race=function(f){return new b(function(h,k){for(var l=r(f),m=l.next();!m.done;m=l.next())d(m.value).R(h,k)})};b.all=function(f){var h=r(f),k=h.next();return k.done?d([]):new b(function(l,m){function t(ha){return function(ia){z[ha]=ia;D--;0==D&&l(z)}}var z=[],D=0;do z.push(void 0),D++,d(k.value).R(t(z.length-1),m),k=h.next();while(!k.done)})};return b});
q("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=r(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!u(k,f)){var l=new c;ba(k,f,{value:l})}}function g(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(t){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&u(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
f)&&u(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,f)&&u(k[f],this.g)?delete k[f][this.g]:!1};return b});
q("Map",function(a){function b(){var h={};return h.H=h.next=h.head=h}function c(h,k){var l=h.g;return da(function(){if(l){for(;l.head!=h.g;)l=l.H;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;"object"==l||"function"==l?g.has(k)?l=g.get(k):(l=""+ ++f,g.set(k,l)):l="p_"+k;var m=h.h[l];if(m&&u(h.h,l))for(h=0;h<m.length;h++){var t=m[h];if(k!==k&&t.key!==t.key||k===t.key)return{id:l,list:m,index:h,A:t}}return{id:l,list:m,
index:-1,A:void 0}}function e(h){this.h={};this.g=b();this.size=0;if(h){h=r(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(r([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(t){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.h[l.id]=[]);l.A?l.A.value=k:(l.A={next:this.g,H:this.g.H,head:this.g,key:h,value:k},l.list.push(l.A),this.g.H.next=l.A,this.g.H=l.A,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.A&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.A.H.next=h.A.next,h.A.next.H=h.A.H,h.A.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.H=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).A};e.prototype.get=function(h){return(h=d(this,h).A)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});q("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,g=0;g<e;g++){var f=d[g];if(b.call(c,f,g,d)){b=f;break a}}b=void 0}return b}});
function Aa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.entries",function(a){return a?a:function(){return Aa(this,function(b,c){return[b,c]})}});q("Array.prototype.keys",function(a){return a?a:function(){return Aa(this,function(b){return b})}});
q("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var f=0;!(g=b.next()).done;)e.push(c.call(d,g.value,f++))}else for(g=b.length,f=0;f<g;f++)e.push(c.call(d,b[f],f));return e}});
q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
q("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});var Ba=Ba||{},w=this||self;
function Ca(a,b){a=a.split(".");var c=w;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Da(a,b){a=a.split(".");b=b||w;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function Ea(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}
function Fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var Ga="closure_uid_"+(1E9*Math.random()>>>0),Ha=0;function Ia(a,b,c){return a.call.apply(a.bind,arguments)}function Ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function x(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?x=Ia:x=Ja;return x.apply(null,arguments)}function y(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function Ka(a){(0,eval)(a)}
function A(a,b){function c(){}c.prototype=b.prototype;a.J=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ba=function(d,e,g){for(var f=Array(arguments.length-2),h=2;h<arguments.length;h++)f[h-2]=arguments[h];return b.prototype[e].apply(d,f)}}function La(a){return a};function B(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,B);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b);this.g=!0}A(B,Error);B.prototype.name="CustomError";var Ma;var Na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Oa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Pa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},Qa=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};function Ra(a,b){b=Na(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}
function Sa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ta=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function Ua(a,b){return a<b?-1:a>b?1:0};function Va(){var a=w.navigator;return a&&(a=a.userAgent)?a:""}function C(a){return-1!=Va().indexOf(a)};function Wa(a){Wa[" "](a);return a}Wa[" "]=function(){};function Xa(a,b){var c=Ya;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Za=C("Opera"),$a=C("Trident")||C("MSIE"),ab=C("Edge"),bb=C("Gecko")&&!(-1!=Va().toLowerCase().indexOf("webkit")&&!C("Edge"))&&!(C("Trident")||C("MSIE"))&&!C("Edge"),cb=-1!=Va().toLowerCase().indexOf("webkit")&&!C("Edge"),db=cb&&C("Mobile"),eb;
a:{var fb="",gb=function(){var a=Va();if(bb)return/rv:([^\);]+)(\)|;)/.exec(a);if(ab)return/Edge\/([\d\.]+)/.exec(a);if($a)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(cb)return/WebKit\/(\S+)/.exec(a);if(Za)return/(?:Version)[ \/]?(\S+)/.exec(a)}();gb&&(fb=gb?gb[1]:"");if($a){var hb,ib=w.document;hb=ib?ib.documentMode:void 0;if(null!=hb&&hb>parseFloat(fb)){eb=String(hb);break a}}eb=fb}var jb=eb,Ya={};
function kb(a){return Xa(a,function(){for(var b=0,c=Ta(String(jb)).split("."),d=Ta(String(a)).split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var f=c[g]||"",h=d[g]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;b=Ua(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||Ua(0==f[2].length,0==h[2].length)||Ua(f[2],h[2]);f=f[3];h=h[3]}while(0==b)}return 0<=b})};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function lb(){};function mb(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function nb(a){var b={},c;for(c in a)b[c]=a[c];return b}var ob="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function pb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<ob.length;g++)c=ob[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var qb;function E(a,b){this.g=b===rb?a:""}E.prototype.toString=function(){return this.g+""};E.prototype.va=!0;E.prototype.ra=function(){return this.g.toString()};function sb(a){return a instanceof E&&a.constructor===E?a.g:"type_error:TrustedResourceUrl"}var rb={};
function tb(a){if(void 0===qb){var b=null;var c=w.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("asx-frontend#html",{createHTML:La,createScript:La,createScriptURL:La})}catch(d){w.console&&w.console.error(d.message)}qb=b}else qb=b}a=(b=qb)?b.createScriptURL(a):a;return new E(a,rb)};function ub(a,b){var c=vb(a.ownerDocument&&a.ownerDocument.defaultView);c&&a.setAttribute("nonce",c);a.src=sb(b)}var wb=/^[\w+/_-]+[=]{0,2}$/;function vb(a){a=(a||w).document;return a.querySelector?(a=a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&wb.test(a)?a:"":""};function xb(a,b){mb(b,function(c,d){c&&"object"==typeof c&&c.va&&(c=c.ra());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:yb.hasOwnProperty(d)?a.setAttribute(yb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var yb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function zb(a,b,c){var d=arguments,e=document,g=d[1],f=Ab(e,String(d[0]));g&&("string"===typeof g?f.className=g:Array.isArray(g)?f.className=g.join(" "):xb(f,g));2<d.length&&Bb(e,f,d);return f}
function Bb(a,b,c){function d(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(var e=2;e<c.length;e++){var g=c[e];if(!Ea(g)||Fa(g)&&0<g.nodeType)d(g);else{a:{if(g&&"number"==typeof g.length){if(Fa(g)){var f="function"==typeof g.item||"string"==typeof g.item;break a}if("function"===typeof g){f="function"==typeof g.item;break a}}f=!1}Oa(f?Sa(g):g,d)}}}function Ab(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}
function Cb(a){this.g=a||w.document||document};var Db={},Eb=null;
function Fb(a){var b;void 0===b&&(b=0);if(!Eb){Eb={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var g=c.concat(d[e].split(""));Db[e]=g;for(var f=0;f<g.length;f++){var h=g[f];void 0===Eb[h]&&(Eb[h]=f)}}}b=Db[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=g=0;g<a.length-2;g+=3){var k=a[g],l=a[g+1];h=a[g+2];f=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|h>>6];h=b[h&63];c[e++]=""+f+k+l+h}f=0;h=d;switch(a.length-g){case 2:f=
a[g+1],h=b[(f&15)<<2]||d;case 1:a=a[g],c[e]=""+b[a>>2]+b[(a&3)<<4|f>>4]+h+d}return c.join("")};var Gb="undefined"!==typeof Uint8Array,Hb={};var Ib;function Jb(a){if(Hb!==Hb)throw Error("illegal external caller");this.ja=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");};var F="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function G(a,b){Object.isFrozen(a)||(F?a[F]|=b:void 0!==a.F?a.F|=b:Object.defineProperties(a,{F:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function Kb(a,b){Object.isExtensible(a)&&(F?a[F]&&(a[F]&=~b):void 0!==a.F&&(a.F&=~b))}function Lb(a){var b;F?b=a[F]:b=a.F;return null==b?0:b}function Mb(a){G(a,1);return a}function H(a){return a?!!(Lb(a)&2):!1}function Nb(a){G(a,16);return a}
function Ob(a){if(!Array.isArray(a))throw Error("cannot mark non-array as shared mutably");Kb(a,16)};function Pb(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Qb=Object.freeze(Mb([]));function Rb(a){if(H(a.o))throw Error("Cannot mutate an immutable Message");}var Sb="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function Tb(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function Ub(a){return a.displayName||a.name||"unknown type name"}function Vb(a,b){if(!(a instanceof b))throw Error("Expected instanceof "+Ub(b)+" but got "+(a&&Ub(a.constructor)));return a};function Wb(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(Gb&&null!=a&&a instanceof Uint8Array)return Fb(a);if(a instanceof Jb){var b=a.ja;b=null==b||"string"===typeof b?b:Gb&&b instanceof Uint8Array?Fb(b):null;return null==b?"":a.ja=b}}}return a};function Xb(a,b,c){if(null!=a){if(Array.isArray(a))a=Yb(a,b,c);else if(Pb(a)){var d={},e;for(e in a)d[e]=Xb(a[e],b,c);a=d}else a=b(a);return a}}function Yb(a,b,c){var d=Array.prototype.slice.call(a);c(a,d);for(a=0;a<d.length;a++)d[a]=Xb(d[a],b,c);return d}function Zb(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=Wb(a);return Array.isArray(a)?Yb(a,Zb,$b):a}function $b(){};function ac(a){return a.h||(a.h=a.o[a.j+a.i]={})}function bc(a,b,c){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:(void 0===c?0:c)&&a.h&&(c=a.h[b],null!=c)?c:a.o[b+a.i]}function cc(a,b,c,d){d=void 0===d?!1:d;Rb(a);a.l&&(a.l=void 0);if(b>=a.j||d)return ac(a)[b]=c,a;if(void 0!==a.h&&a.j>=a.o.length){d=a.o.length-1;var e=b+a.i;e>=d?(a.o[d]=void 0,a.o[e]=c,a.o.push(a.h)):a.o[e]=c}else a.o[b+a.i]=c;void 0!==a.h&&b in a.h&&delete a.h[b];return a}
function I(a,b){a=bc(a,b);a=null==a?a:!!a;return null==a?!1:a}function J(a,b){Rb(a);cc(a,b,void 0,!1);return a}function dc(a,b,c,d){Rb(a);a.g||(a.g={});null==d?b=d=void 0:b=Vb(d,b).o;a.g[c]=d;return cc(a,c,b)};function ec(a,b,c){a||(a=fc);fc=null;var d=this.constructor.g||0,e=0<d,g=this.constructor.h;a?Lb(a)&16&&G(a,32):(a=g?[g]:[],G(a,48));e&&0<a.length&&Pb(a[a.length-1])&&"g"in a[a.length-1]&&(d=0);this.i=(g?0:-1)-d;this.g=void 0;this.o=a;a:{g=this.o.length;d=g-1;if(g&&(g=this.o[d],Pb(g))){this.h=g;b=Object.keys(g);0<b.length&&Qa(b,isNaN)?this.j=Number.MAX_VALUE:this.j=d-this.i;break a}void 0!==b&&-1<b?(this.j=Math.max(b,d+1-this.i),this.h=void 0):this.j=Number.MAX_VALUE}if(!e&&this.h&&"g"in this.h)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');
if(c)for(e=0;e<c.length;e++)b=c[e],b<this.j?(b+=this.i,(d=this.o[b])?Array.isArray(d)&&Mb(d):this.o[b]=Qb):(d=ac(this),(g=d[b])?Array.isArray(g)&&Mb(g):d[b]=Qb)}ec.prototype.toJSON=function(){return Yb(this.o,Zb,$b)};ec.prototype.toString=function(){return this.o.toString()};var fc;function gc(a,b,c,d,e,g){if(a=a.g&&a.g[c])if(Array.isArray(a)){d=g.W?Mb(a.slice()):a;a=0<d.length?d[0].constructor:void 0;Rb(b);if(null!=d){e=Mb([]);g=!1;for(var f=0;f<d.length;f++)e[f]=Vb(d[f],a).o,g=g||H(e[f]);b.g||(b.g={});b.g[c]=d;d=e;g?Kb(d,8):G(d,8)}else b.g&&(b.g[c]=void 0),e=Qb;cc(b,c,e)}else dc(b,a.constructor,c,a);else Gb&&d instanceof Uint8Array?e=d.length?new Jb(new Uint8Array(d)):Ib||(Ib=new Jb(null)):(Array.isArray(d)&&(e?G(d,2):d&&Lb(d)&1&&g.W?(e=Array.prototype.slice.call(d),g=(Lb(d)|
0)&-51,F?e[F]=g:void 0!==e.F?e.F=g:Object.defineProperties(e,{F:{value:g,configurable:!0,writable:!0,enumerable:!1}}),d=e):Ob(d)),e=d),cc(b,c,e)};function hc(){ec.apply(this,arguments)}v(hc,ec);hc.prototype.ia=function(){return this};if(Sb){var ic={};Object.defineProperties(hc,(ic[Symbol.hasInstance]=Tb(function(){throw Error(void 0);}),ic))};function K(){hc.apply(this,arguments)}v(K,hc);K.prototype.ia=function(){if(H(this.o)){var a={W:!0};var b=H(this.o);if(b&&!a.W)throw Error("copyRepeatedFields must be true for frozen messages");b||Ob(this.o);var c=new this.constructor;this.m&&(c.m=this.m.slice());for(var d=this.o,e=0;e<d.length;e++){var g=d[e];if(e===d.length-1&&Pb(g))for(var f in g){var h=+f;Number.isNaN(h)?ac(c)[f]=g[f]:gc(this,c,h,g[f],b,a)}else gc(this,c,e-this.i,g,b,a)}c.l=this;a=c}else a=this;return a};
if(Sb){var jc={};Object.defineProperties(K,(jc[Symbol.hasInstance]=Tb(Object[Symbol.hasInstance]),jc))};function kc(a){var b=w.onerror;w.onerror=function(c,d,e,g,f){b&&b(c,d,e,g,f);a({message:c,fileName:d,line:e,lineNumber:e,Da:g,error:f});return!1}}
function lc(a){var b=Da("window.location.href");null==a&&(a='Unknown Error of type "null/undefined"');if("string"===typeof a)return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"};var c=!1;try{var d=a.lineNumber||a.line||"Not available"}catch(f){d="Not available",c=!0}try{var e=a.fileName||a.filename||a.sourceURL||w.$googDebugFname||b}catch(f){e="Not available",c=!0}b=mc(a);if(!(!c&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name)){c=a.message;if(null==
c){if(a.constructor&&a.constructor instanceof Function){if(a.constructor.name)c=a.constructor.name;else if(c=a.constructor,nc[c])c=nc[c];else{c=String(c);if(!nc[c]){var g=/function\s+([^\(]+)/m.exec(c);nc[c]=g?g[1]:"[Anonymous]"}c=nc[c]}c='Unknown Error of type "'+c+'"'}else c="Unknown Error of unknown type";"function"===typeof a.toString&&Object.prototype.toString!==a.toString&&(c+=": "+a.toString())}return{message:c,name:a.name||"UnknownError",lineNumber:d,fileName:e,stack:b||"Not available"}}a.stack=
b;return{message:a.message,name:a.name,lineNumber:a.lineNumber,fileName:a.fileName,stack:a.stack}}function mc(a,b){b||(b={});b[oc(a)]=!0;var c=a.stack||"";(a=a.cause)&&!b[oc(a)]&&(c+="\nCaused by: ",a.stack&&0==a.stack.indexOf(a.toString())||(c+="string"===typeof a?a:a.message+"\n"),c+=mc(a,b));return c}function oc(a){var b="";"function"===typeof a.toString&&(b=""+a);return b+a.stack}var nc={};/*

 SPDX-License-Identifier: Apache-2.0
*/
function pc(a){var b,c,d=null==(c=(b=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:c.call(b,"script[nonce]");(b=d?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b)};function qc(a){var b=za.apply(1,arguments);if(0===b.length)return tb(a[0]);for(var c=[a[0]],d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return tb(c.join(""))};function rc(a,b){this.i=a;this.j=b;this.h=0;this.g=null}rc.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function sc(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};var tc=[],uc=[],vc=!1;function wc(a){tc[tc.length]=a;if(vc)for(var b=0;b<uc.length;b++)a(x(uc[b].g,uc[b]))};var xc;
function yc(){var a=w.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!C("Presto")&&(a=function(){var e=Ab(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var g=e.contentWindow;e=g.document;e.open();e.close();var f="callImmediate"+Math.random(),h="file:"==g.location.protocol?"*":g.location.protocol+"//"+g.location.host;e=x(function(k){if(("*"==h||k.origin==h)&&k.data==f)this.port1.onmessage()},this);
g.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){g.postMessage(f,h)}}});if("undefined"!==typeof a&&!C("Trident")&&!C("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.ca;c.ca=null;e()}};return function(e){d.next={ca:e};d=d.next;b.port2.postMessage(0)}}return function(e){w.setTimeout(e,0)}}function zc(a){return a}wc(function(a){zc=a});function Ac(a){w.setTimeout(function(){throw a;},0)};function Bc(){this.h=this.g=null}Bc.prototype.add=function(a,b){var c=Cc.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function Dc(){var a=Ec,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var Cc=new rc(function(){return new Fc},function(a){return a.reset()});function Fc(){this.next=this.scope=this.g=null}Fc.prototype.set=function(a,b){this.g=a;this.scope=b;this.next=null};Fc.prototype.reset=function(){this.next=this.scope=this.g=null};var Gc,Hc=!1,Ec=new Bc;function Ic(a,b){Gc||Jc();Hc||(Gc(),Hc=!0);Ec.add(a,b)}function Jc(){if(w.Promise&&w.Promise.resolve){var a=w.Promise.resolve(void 0);Gc=function(){a.then(Kc)}}else Gc=function(){var b=Kc;b=zc(b);"function"!==typeof w.setImmediate||w.Window&&w.Window.prototype&&!C("Edge")&&w.Window.prototype.setImmediate==w.setImmediate?(xc||(xc=yc()),xc(b)):w.setImmediate(b)}}function Kc(){for(var a;a=Dc();){try{a.g.call(a.scope)}catch(b){Ac(b)}sc(Cc,a)}Hc=!1};function L(){this.l=this.l;this.s=this.s}L.prototype.l=!1;L.prototype.isDisposed=function(){return this.l};L.prototype.X=function(){this.l||(this.l=!0,this.G())};L.prototype.G=function(){if(this.s)for(;this.s.length;)this.s.shift()()};function M(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}M.prototype.h=function(){this.defaultPrevented=!0};function N(a,b){M.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}A(N,M);var Lc={2:"touch",3:"pen",4:"mouse"};
N.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(bb){a:{try{Wa(b.nodeName);var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||
0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Lc[a.pointerType]||"";this.state=a.state;this.i=a;a.defaultPrevented&&N.J.h.call(this)};
N.prototype.h=function(){N.J.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var Mc="closure_listenable_"+(1E6*Math.random()|0);var Nc=0;function Oc(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.T=e;this.key=++Nc;this.N=this.P=!1}function Pc(a){a.N=!0;a.listener=null;a.proxy=null;a.src=null;a.T=null};function Qc(a){this.src=a;this.g={};this.h=0}Qc.prototype.add=function(a,b,c,d,e){var g=a.toString();a=this.g[g];a||(a=this.g[g]=[],this.h++);var f=Rc(a,b,d,e);-1<f?(b=a[f],c||(b.P=!1)):(b=new Oc(b,this.src,g,!!d,e),b.P=c,a.push(b));return b};function Sc(a,b){var c=b.type;c in a.g&&Ra(a.g[c],b)&&(Pc(b),0==a.g[c].length&&(delete a.g[c],a.h--))}function Rc(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.N&&g.listener==b&&g.capture==!!c&&g.T==d)return e}return-1};var Tc="closure_lm_"+(1E6*Math.random()|0),Uc={},Vc=0;function Wc(a,b,c,d,e){if(Array.isArray(b))for(var g=0;g<b.length;g++)Wc(a,b[g],c,d,e);else(d=Fa(d)?!!d.capture:!!d,c=Xc(c),a&&a[Mc])?(a=a.i,b=String(b).toString(),b in a.g&&(g=a.g[b],c=Rc(g,c,d,e),-1<c&&(Pc(g[c]),Array.prototype.splice.call(g,c,1),0==g.length&&(delete a.g[b],a.h--)))):a&&(a=Yc(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Rc(b,c,d,e)),(c=-1<a?b[a]:null)&&Zc(c))}
function Zc(a){if("number"!==typeof a&&a&&!a.N){var b=a.src;if(b&&b[Mc])Sc(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(c in Uc?Uc[c]:Uc[c]="on"+c,d):b.addListener&&b.removeListener&&b.removeListener(d);Vc--;(c=Yc(b))?(Sc(c,a),0==c.h&&(c.src=null,b[Tc]=null)):Pc(a)}}}function $c(a,b){if(a.N)a=!0;else{b=new N(b,this);var c=a.listener,d=a.T||a.src;a.P&&Zc(a);a=c.call(d,b)}return a}
function Yc(a){a=a[Tc];return a instanceof Qc?a:null}var ad="__closure_events_fn_"+(1E9*Math.random()>>>0);function Xc(a){if("function"===typeof a)return a;a[ad]||(a[ad]=function(b){return a.handleEvent(b)});return a[ad]}wc(function(a){$c=a($c)});function O(){L.call(this);this.i=new Qc(this);this.la=this;this.L=null}A(O,L);O.prototype[Mc]=!0;O.prototype.removeEventListener=function(a,b,c,d){Wc(this,a,b,c,d)};
function P(a,b){var c=a.L;if(c){var d=[];for(var e=1;c;c=c.L)d.push(c),++e}a=a.la;c=b.type||b;"string"===typeof b?b=new M(b,a):b instanceof M?b.target=b.target||a:(e=b,b=new M(c,a),pb(b,e));e=!0;if(d)for(var g=d.length-1;0<=g;g--){var f=b.g=d[g];e=bd(f,c,!0,b)&&e}f=b.g=a;e=bd(f,c,!0,b)&&e;e=bd(f,c,!1,b)&&e;if(d)for(g=0;g<d.length;g++)f=b.g=d[g],e=bd(f,c,!1,b)&&e}
O.prototype.G=function(){O.J.G.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,Pc(d[e]);delete a.g[c];a.h--}}this.L=null};function bd(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,g=0;g<b.length;++g){var f=b[g];if(f&&!f.N&&f.capture==c){var h=f.listener,k=f.T||f.src;f.P&&Sc(a.i,f);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};function cd(a){try{return w.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function dd(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};function ed(){}ed.prototype.h=null;function fd(a){return a.h||(a.h=a.j())};var gd;function hd(){}A(hd,ed);hd.prototype.g=function(){var a=id(this);return a?new ActiveXObject(a):new XMLHttpRequest};hd.prototype.j=function(){var a={};id(this)&&(a[0]=!0,a[1]=!0);return a};
function id(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i}gd=new hd;function jd(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function Q(a){this.g=0;this.s=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=lb)try{var b=this;a.call(void 0,function(c){R(b,2,c)},function(c){R(b,3,c)})}catch(c){R(this,3,c)}}function kd(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1}kd.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};var ld=new rc(function(){return new kd},function(a){a.reset()});function md(a,b,c){var d=ld.get();d.j=a;d.h=b;d.i=c;return d}
function S(a){if(a instanceof Q)return a;var b=new Q(lb);R(b,2,a);return b}function nd(a,b,c){od(a,b,c,null)||Ic(y(b,a))}function pd(a){return new Q(function(b){var c=a.length,d=[];if(c)for(var e=function(h,k,l){c--;d[h]=k?{qa:!0,value:l}:{qa:!1,reason:l};0==c&&b(d)},g=0,f;g<a.length;g++)f=a[g],nd(f,y(e,g,!0),y(e,g,!1));else b(d)})}Q.prototype.then=function(a,b,c){return qd(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};Q.prototype.$goog_Thenable=!0;
function T(a,b){return qd(a,null,b)}Q.prototype.cancel=function(a){if(0==this.g){var b=new U(a);Ic(function(){rd(this,b)},this)}};function rd(a,b){if(0==a.g)if(a.i){var c=a.i;if(c.h){for(var d=0,e=null,g=null,f=c.h;f&&(f.l||(d++,f.g==a&&(e=f),!(e&&1<d)));f=f.next)e||(g=f);e&&(0==c.g&&1==d?rd(c,b):(g?(d=g,d.next==c.j&&(c.j=d),d.next=d.next.next):sd(c),td(c,e,3,b)))}a.i=null}else R(a,3,b)}function ud(a,b){a.h||2!=a.g&&3!=a.g||vd(a);a.j?a.j.next=b:a.h=b;a.j=b}
function qd(a,b,c,d){var e=md(null,null,null);e.g=new Q(function(g,f){e.j=b?function(h){try{var k=b.call(d,h);g(k)}catch(l){f(l)}}:g;e.h=c?function(h){try{var k=c.call(d,h);void 0===k&&h instanceof U?f(h):g(k)}catch(l){f(l)}}:f});e.g.i=a;ud(a,e);return e.g}Q.prototype.v=function(a){this.g=0;R(this,2,a)};Q.prototype.B=function(a){this.g=0;R(this,3,a)};
function R(a,b,c){0==a.g&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.g=1,od(c,a.v,a.B,a)||(a.s=c,a.g=b,a.i=null,vd(a),3!=b||c instanceof U||wd(a,c)))}function od(a,b,c,d){if(a instanceof Q)return ud(a,md(b||lb,c||null,d)),!0;if(jd(a))return a.then(b,c,d),!0;if(Fa(a))try{var e=a.then;if("function"===typeof e)return xd(a,e,b,c,d),!0}catch(g){return c.call(d,g),!0}return!1}
function xd(a,b,c,d,e){function g(k){h||(h=!0,d.call(e,k))}function f(k){h||(h=!0,c.call(e,k))}var h=!1;try{b.call(a,f,g)}catch(k){g(k)}}function vd(a){a.m||(a.m=!0,Ic(a.u,a))}function sd(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b}Q.prototype.u=function(){for(var a;a=sd(this);)td(this,a,this.g,this.s);this.m=!1};
function td(a,b,c,d){if(3==c&&b.h&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,yd(b,c,d);else try{b.l?b.j.call(b.i):yd(b,c,d)}catch(e){zd.call(null,e)}sc(ld,b)}function yd(a,b,c){2==b?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)}function wd(a,b){a.l=!0;Ic(function(){a.l&&zd.call(null,b)})}var zd=Ac;function U(a){B.call(this,a);this.g=!1}A(U,B);U.prototype.name="cancel";function Ad(a,b,c){if("function"===typeof a)c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:w.setTimeout(a,b||0)};var Bd=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Cd(a){a=a.match(Bd)[1]||null;!a&&w.self&&w.self.location&&(a=w.self.location.protocol.slice(0,-1));return a?a.toLowerCase():""}
function Dd(a,b){if(!b)return a;var c=a.indexOf("#");0>c&&(c=a.length);var d=a.indexOf("?");if(0>d||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}function Ed(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)Ed(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))}function Fd(a,b){var c=[];for(b=b||0;b<a.length;b+=2)Ed(a[b],a[b+1],c);return c.join("&")}
function Gd(a){var b=[],c;for(c in a)Ed(c,a[c],b);return b.join("&")}function Hd(a,b){var c=2==arguments.length?Fd(arguments[1],0):Fd(arguments,1);return Dd(a,c)};function Id(a){O.call(this);this.headers=new Map;this.C=a||null;this.h=!1;this.B=this.g=null;this.K="";this.j=this.I=this.m=this.D=!1;this.v=0;this.u=null;this.Z="";this.U=this.V=!1}A(Id,O);var Jd=/^https?$/i,Kd=["POST","PUT"],Ld=[];function Md(a,b,c,d,e,g,f){var h=new Id;Ld.push(h);b&&h.i.add("complete",b,!1,void 0,void 0);h.i.add("ready",h.na,!0,void 0,void 0);g&&(h.v=Math.max(0,g));f&&(h.V=f);Nd(h,a,c,d,e)}n=Id.prototype;n.na=function(){this.X();Ra(Ld,this)};
function Nd(a,b,c,d,e){if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.K+"; newUri="+b);c=c?c.toUpperCase():"GET";a.K=b;a.D=!1;a.h=!0;a.g=a.C?a.C.g():gd.g();a.B=a.C?fd(a.C):fd(gd);a.g.onreadystatechange=x(a.da,a);try{a.I=!0,a.g.open(c,String(b),!0),a.I=!1}catch(h){Od(a);return}b=d||"";d=new Map(a.headers);if(e)if(Object.getPrototypeOf(e)===Object.prototype)for(var g in e)d.set(g,e[g]);else if("function"===typeof e.keys&&"function"===typeof e.get){g=r(e.keys());for(var f=
g.next();!f.done;f=g.next())f=f.value,d.set(f,e.get(f))}else throw Error("Unknown input type for opt_headers: "+String(e));e=Array.from(d.keys()).find(function(h){return"content-type"==h.toLowerCase()});g=w.FormData&&b instanceof w.FormData;!(0<=Na(Kd,c))||e||g||d.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");c=r(d);for(e=c.next();!e.done;e=c.next())d=r(e.value),e=d.next().value,d=d.next().value,a.g.setRequestHeader(e,d);a.Z&&(a.g.responseType=a.Z);"withCredentials"in a.g&&
a.g.withCredentials!==a.V&&(a.g.withCredentials=a.V);try{Pd(a),0<a.v&&(a.U=Qd(a.g),a.U?(a.g.timeout=a.v,a.g.ontimeout=x(a.O,a)):a.u=Ad(a.O,a.v,a)),a.m=!0,a.g.send(b),a.m=!1}catch(h){Od(a)}}function Qd(a){return $a&&kb(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout}n.O=function(){"undefined"!=typeof Ba&&this.g&&(P(this,"timeout"),this.abort(8))};function Od(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);Rd(a);Sd(a)}function Rd(a){a.D||(a.D=!0,P(a,"complete"),P(a,"error"))}
n.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,P(this,"complete"),P(this,"abort"),Sd(this))};n.G=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),Sd(this,!0));Id.J.G.call(this)};n.da=function(){this.isDisposed()||(this.I||this.m||this.j?Td(this):this.Y())};n.Y=function(){Td(this)};
function Td(a){if(a.h&&"undefined"!=typeof Ba&&(!a.B[1]||4!=(a.g?a.g.readyState:0)||2!=Ud(a)))if(a.m&&4==(a.g?a.g.readyState:0))Ad(a.da,0,a);else if(P(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.h=!1;try{var b=Ud(a),c;if(!(c=dd(b))){var d;if(d=0===b){var e=Cd(String(a.K));d=!Jd.test(e)}c=d}c?(P(a,"complete"),P(a,"success")):Rd(a)}finally{Sd(a)}}}function Sd(a,b){if(a.g){Pd(a);var c=a.g,d=a.B[0]?function(){}:null;a.g=null;a.B=null;b||P(a,"ready");try{c.onreadystatechange=d}catch(e){}}}
function Pd(a){a.g&&a.U&&(a.g.ontimeout=null);a.u&&(w.clearTimeout(a.u),a.u=null)}n.isActive=function(){return!!this.g};function Ud(a){try{return 2<(a.g?a.g.readyState:0)?a.g.status:-1}catch(b){return-1}}wc(function(a){Id.prototype.Y=a(Id.prototype.Y)});function Vd(a){K.call(this,a)}v(Vd,K);n=Vd.prototype;n.getEnableSsEngine=function(){return I(this,2)};n.getEnableAwr=function(){return I(this,3)};n.getEnableHelpSuggestions=function(){return I(this,4)};n.getAlohaAutoGaRollout=function(){return I(this,5)};n.getEnableConfigurator=function(){return I(this,6)};n.getEnableMweb=function(){return I(this,7)};n.getEnableCtlConsentCheckbox=function(){return I(this,8)};n.getEnableIframe=function(){return I(this,9)};
n.getEnableScreenshotNudge=function(){return I(this,10)};function Wd(a){K.call(this,a)}v(Wd,K);var Xd=["https://sandbox.google.com/tools/feedback"];var Yd="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");
function Zd(a){var b;return null==(b=a.formContent)?void 0:b.locale};var $d=ea(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);function ae(a){var b=Zd(a);b=(b&&Yd.includes(b)?Zd(a):"en").replaceAll("-","_").toLowerCase();var c;a=(null==(c=a.initializationData)?0:c.useNightlyRelease)?"nightly":"live";return qc($d,a,b)};var be;function ce(a,b,c){if(be)return be;var d=ae(a);return be=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(e,g){var f=c.createElement("script");f.src=sb(d);pc(f);f.onload=function(){b.feedbackV2GlobalObject?e(b.feedbackV2GlobalObject):g("feedbackV2GlobalObject not found on window.")};f.onerror=function(){g("Feedback binary script tag failed to load: "+d.toString())};c.body.appendChild(f)})}
function de(a,b,c,d,e){e=void 0===e?!0:e;var g,f,h,k,l;return ya(function(m){switch(m.h){case 1:g=Date.now();var t=ce(a,c,d);m.h=2;return{value:t};case 2:f=m.l;if(!(e||(null==(k=a.initializationData)?0:k.useNightlyRelease)||(null==(l=a.initializationData)?0:l.isLocalServer))){h=f.initializeFeedbackClient(a,g,b);m.h=3;break}t=f.initializeFeedbackClientAsync(a,g,b);m.h=4;return{value:t};case 4:h=m.l;case 3:return h.initiateAloha(),m.return(h)}})}
function ee(a,b,c){var d=!0;d=void 0===d?!0:d;var e,g,f,h;ya(function(k){g=e=c||w;if(g.isFormOpened)throw f=Error("Form is either loading or already opened"),f.name="DuplicateFormError",f;g.isFormOpened=!0;a.callbacks=a.callbacks||{};h=a.callbacks.onClose||function(){};a.callbacks.onClose=function(l){g.isFormOpened=!1;h(l)};try{return k.return(de(a,b,g,e.document,d))}catch(l){throw g.isFormOpened=!1,l;}})};function fe(a,b){return ya(function(c){return c.return(new Promise(function(d){var e=ge(null!=b?b:"")+"/aloha_form_properties?productId="+a;Md(e,function(g){var f=g.target;g=null;try{var h=JSON,k=h.stringify;if(f.g){var l=f.g.responseText;0==l.indexOf(")]}'\n")&&(l=l.substring(5));b:{if(w.JSON)try{var m=w.JSON.parse(l);break b}catch(ia){}m=cd(l)}}else m=void 0;var t=k.call(h,m);if(null==t||""==t)g=new Wd;else{var z=JSON.parse(t);if(!Array.isArray(z))throw Error(void 0);var D=Nb(z);fc=D;var ha=new Wd(D);
fc=null;g=ha}}catch(ia){k=new Wd,m=new Vd,m=J(m,5),m=J(m,2),m=J(m,4),m=J(m,8),m=J(m,9),m=J(m,7),m=J(m,10),g=dc(k,Vd,1,m)}d(g)},"GET","",{},2E3,!0)}))})}function ge(a){return Xd.includes(a)?a:"https://www.google.com/tools/feedback"};function he(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||w,e=d.document,g=a.nonce||vb(d);g&&!a.nonce&&(a.nonce=g);if("help"==a.flow){var f=Da("document.location.href",d);!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(f=1200>=h.length)&&(a.psdJson=h)}f||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(f=d.GOOGLE_FEEDBACK_START)f.apply(d,
b);else{d=c+"/load.js?";for(var k in a)b=a[k],null==b||Fa(b)||(d+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=Ab((e?new Cb(9==e.nodeType?e:e.ownerDocument||e.document):Ma||(Ma=new Cb)).g,"SCRIPT");g&&a.setAttribute("nonce",g);g=tb(d);a.src=sb(g);pc(a);e.body.appendChild(a)}}
Ca("userfeedback.api.startFeedback",function(a,b,c){try{"submit"===a.flow||"help"===a.flow||a.tinyNoPointer?he(a,b,c):fe(a.productId,a.feedbackServerUri).then(function(d){var e=void 0===e?!1:e;d.g||(d.g={});var g=d.g[1];if(g)var f=g;else{g=bc(d,1,e);f=void 0===f?!1:f;var h=void 0===h?!1:h;f=Array.isArray(g)?new Vd(h?Nb(g):g):f?new Vd:void 0;f&&(d.g[1]=f,G(f.o,Lb(d.o)&-33))}null!=f&&H(f.o)&&!H(d.o)&&(f=f.ia(),cc(d,1,f.o,e),d.g[1]=f);d=f;null==d||!d.getAlohaAutoGaRollout()||db&&!d.getEnableMweb()?he(a,
b,c):(e=c||w,f="DEV"===a.serverEnvironment,h=c||w,h=a.nonce||vb(h),f={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,Ea:void 0,defaultFormInputValues:void 0,defaultFormInputValuesString:void 0,abuseLink:a.abuseLink},
initializationData:{isLocalServer:f,nonce:h,useNightlyRelease:f,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,enableAnonymousFeedback:a.enableAnonymousFeedback}},b&&(h=new Map(Object.entries(b)),
f.extraData.productSpecificData=h),ee(f,d,e))},function(d){d&&"DuplicateFormError"!==d.name&&he(a,b,c)})}catch(d){he(a,b,c)}});function ie(a){a=void 0===a?{}:a;this.useNotifications=a.useNotifications||!1;this.operatorDeferredUrl=a.operatorDeferredUrl;this.alphaTestMode=a.alphaTestMode||!1;this.stagingMode=a.stagingMode||!1;this.rosterId=a.rosterId||"talk_roster";this.feedbackId=a.feedbackId||74772;this.moleVersion=a.moleVersion||void 0;this.gstaticBaseUrl=a.gstaticBaseUrl||void 0;this.operatorDeferredBaseUrl=a.operatorDeferredBaseUrl||void 0;this.forceLeftMoles=a.forceLeftMoles||void 0;this.helpCenterName=a.helpCenterName||
null;this.localeName=a.localeName||null;this.document=a.document||document;this.source=a.source||void 0;this.entityId=a.entityId||void 0;this.authUser=a.authUser||void 0;this.appDomain=a.appDomain||void 0;this.apiKey=a.apiKey||void 0;this.hideQueueWidget=a.hideQueueWidget||!1;this.hideMoles=a.hideMoles||!1;this.enableMinimizeRestoreKeyboardShortcut=a.enableMinimizeRestoreKeyboardShortcut||!1;this.showSecondsInChatTranscript=a.showSecondsInChatTranscript||!1;this.settings=a.settings||void 0;this.jsHint=
a.jsHint||void 0;this.xhrTimeoutMs=a.xhrTimeoutMs||1E4;this.enableChatSmartReply=a.enableChatSmartReply||!1;this.isCasesHostPage=a.isCasesHostPage||!1};function je(){};/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
function V(a,b){this.l=[];this.D=a;this.C=b||null;this.j=this.i=!1;this.h=void 0;this.v=this.I=this.s=!1;this.m=0;this.g=null;this.u=0}A(V,je);V.prototype.cancel=function(a){if(this.i)this.h instanceof V&&this.h.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.u--,0>=b.u&&b.cancel())}this.D?this.D.call(this.C,this):this.v=!0;this.i||(a=new ke(this),le(this),me(this,!1,a))}};V.prototype.B=function(a,b){this.s=!1;me(this,a,b)};function me(a,b,c){a.i=!0;a.h=c;a.j=!b;ne(a)}
function le(a){if(a.i){if(!a.v)throw new oe(a);a.v=!1}}V.prototype.callback=function(a){le(this);me(this,!0,a)};function pe(a,b,c,d){a.l.push([b,c,d]);a.i&&ne(a)}V.prototype.then=function(a,b,c){var d,e,g=new Q(function(f,h){e=f;d=h});pe(this,e,function(f){f instanceof ke?g.cancel():d(f);return qe},this);return g.then(a,b,c)};V.prototype.$goog_Thenable=!0;function re(a){return Pa(a.l,function(b){return"function"===typeof b[1]})}var qe={};
function ne(a){if(a.m&&a.i&&re(a)){var b=a.m,c=se[b];c&&(w.clearTimeout(c.g),delete se[b]);a.m=0}a.g&&(a.g.u--,delete a.g);b=a.h;for(var d=c=!1;a.l.length&&!a.s;){var e=a.l.shift(),g=e[0],f=e[1];e=e[2];if(g=a.j?f:g)try{var h=g.call(e||a.C,b);h===qe&&(h=void 0);void 0!==h&&(a.j=a.j&&(h==b||h instanceof Error),a.h=b=h);if(jd(b)||"function"===typeof w.Promise&&b instanceof w.Promise)d=!0,a.s=!0}catch(k){b=k,a.j=!0,re(a)||(c=!0)}}a.h=b;d&&(h=x(a.B,a,!0),d=x(a.B,a,!1),b instanceof V?(pe(b,h,d),b.I=!0):
b.then(h,d));c&&(b=new te(b),se[b.g]=b,a.m=b.g)}function oe(){B.call(this)}A(oe,B);oe.prototype.message="Deferred has already fired";oe.prototype.name="AlreadyCalledError";function ke(){B.call(this)}A(ke,B);ke.prototype.message="Deferred was canceled";ke.prototype.name="CanceledError";function te(a){this.g=w.setTimeout(x(this.i,this),0);this.h=a}te.prototype.i=function(){delete se[this.g];throw this.h;};var se={};function ue(a,b){var c=b||{};b=c.document||document;var d=sb(a).toString(),e=Ab((new Cb(b)).g,"SCRIPT"),g={ea:e,O:void 0},f=new V(ve,g),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){we(e,!0);var l=new xe(1,"Timeout reached for loading script "+d);le(f);me(f,!1,l)},k),g.O=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(we(e,c.Ca||!1,h),f.callback(null))};e.onerror=function(){we(e,!0,h);var l=new xe(0,"Error while loading script "+
d);le(f);me(f,!1,l)};g=c.attributes||{};pb(g,{type:"text/javascript",charset:"UTF-8"});xb(e,g);ub(e,a);ye(b).appendChild(e);return f}function ye(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!==b.length?b[0]:a.documentElement}function ve(){if(this&&this.ea){var a=this.ea;a&&"SCRIPT"==a.tagName&&we(a,!0,this.O)}}
function we(a,b,c){null!=c&&w.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function xe(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);B.call(this,c);this.code=a}A(xe,B);function ze(a,b){return Ae(a,b).then(function(c){var d=c.responseText;b&&b.Aa&&(c=b.Aa,0==d.lastIndexOf(c,0)&&(d=d.substring(c.length)));return JSON.parse(d)})}
function Ae(a,b){var c=b||{},d=c.ka?c.ka.g():gd.g();return T(new Q(function(e,g){var f;try{d.open("GET",a,!0)}catch(l){g(new W("Error opening XHR: "+l.message,a,d))}d.onreadystatechange=function(){if(4==d.readyState){w.clearTimeout(f);var l;!(l=dd(d.status))&&(l=0===d.status)&&(l=Cd(a),l=!("http"==l||"https"==l||""==l));l?e(d):g(new Be(d.status,a,d))}};d.onerror=function(){g(new W("Network error",a,d))};if(c.headers)for(var h in c.headers){var k=c.headers[h];null!=k&&d.setRequestHeader(h,k)}c.withCredentials&&
(d.withCredentials=c.withCredentials);c.responseType&&(d.responseType=c.responseType);c.mimeType&&d.overrideMimeType(c.mimeType);0<c.ha&&(f=w.setTimeout(function(){d.onreadystatechange=function(){};d.abort();g(new Ce(a,d))},c.ha));try{d.send(null)}catch(l){d.onreadystatechange=function(){},w.clearTimeout(f),g(new W("Error sending XHR: "+l.message,a,d))}}),function(e){e instanceof U&&d.abort();throw e;})}function W(a,b){B.call(this,a+", url="+b);this.url=b}A(W,B);W.prototype.name="XhrError";
function Be(a,b,c){W.call(this,"Request Failed, status="+a,b,c);this.status=a}A(Be,W);Be.prototype.name="XhrHttpError";function Ce(a,b){W.call(this,"Request timed out",a,b)}A(Ce,W);Ce.prototype.name="XhrTimeoutError";function De(){}A(De,ed);De.prototype.g=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if("undefined"!=typeof XDomainRequest)return new Ee;throw Error("Unsupported browser");};De.prototype.j=function(){return{}};
function Ee(){this.g=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText="";this.status=-1;this.statusText="";this.g.onload=x(this.sa,this);this.g.onerror=x(this.aa,this);this.g.onprogress=x(this.ta,this);this.g.ontimeout=x(this.ua,this)}n=Ee.prototype;n.open=function(a,b,c){if(null!=c&&!c)throw Error("Only async requests are supported.");this.g.open(a,b)};
n.send=function(a){if(a)if("string"==typeof a)this.g.send(a);else throw Error("Only string data is supported");else this.g.send()};n.abort=function(){this.g.abort()};n.setRequestHeader=function(){};n.getResponseHeader=function(a){return"content-type"==a.toLowerCase()?this.g.contentType:""};n.sa=function(){this.status=200;this.responseText=this.g.responseText;Fe(this,4)};n.aa=function(){this.status=500;this.responseText="";Fe(this,4)};n.ua=function(){this.aa()};
n.ta=function(){this.status=200;Fe(this,1)};function Fe(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}n.getAllResponseHeaders=function(){return"content-type: "+this.g.contentType};function Ge(a){this.config=a instanceof ie?a:new ie(a);this.config=He(this.config);this.g=Ie(this);this.i=this.config.moleVersion?S():this.g.then(function(b){this.config.moleVersion=b.cbfVersion},function(){},this);this.j=this.g.then(function(b){this.config.settings=this.config.settings?Object.assign({},b.settings,this.config.settings):b.settings},function(){},this);this.g.then(this.h,function(){},this)}
function Ie(a){return ze(a.config.alphaTestMode?"//ssl.gstatic.com/support/realtime/operatorParamsDev":a.config.stagingMode?"//ssl.gstatic.com/support/realtime/operatorParamsStaging":"//ssl.gstatic.com/support/realtime/operatorParams",{ha:a.config.xhrTimeoutMs,ka:new De}).then(function(b){if(!b)throw Error("operatorParams is null");return b},function(b){throw b;})}
function Je(a){var b=Ke();if(b)return b;if(b=Le())return b=S(b),Me(b),b;b=pd([a.i,a.j]).then(function(){return Ne(a).then(function(c){var d={document:this.config.document,timeout:this.config.xhrTimeoutMs};this.config.operatorDeferredUrl=c;try{return ue(tb(c),d).then(function(){return w.cs.OperatorDeferred.getInstance(this.config)},function(e){throw e;},this)}catch(e){throw e;}},null,a)},function(){},a);Me(b);return b}
Ge.prototype.h=function(a){(new RegExp(a.eagerLoadHostnamePattern,a.eagerLoadHostnameFlags)).test(this.config.document.location.href)&&T(Je(this),y(Oe,"Error retrieving OperatorDeferred"))};
function Ne(a){return a.config.operatorDeferredUrl?S(a.config.operatorDeferredUrl):a.config.operatorDeferredBaseUrl?(a=a.config.operatorDeferredBaseUrl+"/"+a.config.moleVersion+"/operatordeferred_bin_base__"+a.config.localeName.replace(/-/g,"_").toLowerCase()+".js",S(a)):a.g.then(x(function(b){return"https://ssl.gstatic.com/support/realtime/operator/"+b.cbfVersion+"/operatordeferred_bin_base__"+this.config.localeName.replace(/-/g,"_").toLowerCase()+".js"},a),function(b){throw b;})}
function Pe(a,b){return Je(a).then(y(function(c,d){d.registerAvailabilityCallbacks(c)},b))}function Qe(a){return Je(a).then(function(b){b.getAvailabilities()})}Ge.prototype.S=function(){return Je(this).then(function(a){a.ensureSubscribed()})};function Re(a,b,c){b=y(function(d,e,g,f,h,k){return k.requestSupport(d,e,g,f,h)},b,c,void 0,!0,void 0);return(c=Le())?(a=b(c),S(a)):Je(a).then(b)}function Le(){return Da("cs.operatorDeferredInstance")}
function Ke(){var a=Da("cs.operatorDeferredPromise");return a instanceof Q?a:null!=a?S(a):null}function Me(a){Ca("cs.operatorDeferredPromise",a)}function Oe(){}function He(a){a=nb(a);a.document=a.document||document;null!=a.localeName&&(a.localeName=a.localeName.replace(/_/g,"-"));a.localeName=a.localeName&&0<=Na(Se,a.localeName)?a.localeName:"en";a.helpCenterName=a.helpCenterName||"chatsupport";a.apiKey=a.apiKey||"AIzaSyB5V4SIBGmrqREm7kf2fBJgPcBMCdUrLzE";return a}var Se="af am ar ar-XB bg bn ca cs da de el en en-AU en-GB en-XA en-XC es es-419 et eu fa fi fil fr gl gu hi hr hu id is it iw ja kn ko lt lv ml mr ms nl no pl pt-PT pt-BR ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW zh-HK zu".split(" ");function Te(a){Ge.call(this,a)}v(Te,Ge);function Ue(a){L.call(this);this.h=a}A(Ue,L);Ue.prototype.g=function(a){return Ve(this,a)};function We(a,b){a=Object.prototype.hasOwnProperty.call(a,Ga)&&a[Ga]||(a[Ga]=++Ha);return(b?"__wrapper_":"__protected_")+a+"__"}function Ve(a,b){var c=We(a,!0);b[c]||((b[c]=Xe(a,b))[We(a,!1)]=b);return b[c]}
function Xe(a,b){function c(){if(a.isDisposed())return b.apply(this,arguments);try{return b.apply(this,arguments)}catch(e){var d=e;if(!(d&&"object"===typeof d&&"string"===typeof d.message&&0==d.message.indexOf("Error in protected function: ")||"string"===typeof d&&0==d.indexOf("Error in protected function: ")))throw a.h(d),new Ye(d);}}c[We(a,!1)]=b;return c}
function Ze(a,b){var c=w.window,d=c[b];if(!d)throw Error(b+" not on global?");c[b]=function(e,g){"string"===typeof e&&(e=y(Ka,e));e&&(arguments[0]=e=Ve(a,e));if(d.apply)return d.apply(this,arguments);var f=e;if(2<arguments.length){var h=Array.prototype.slice.call(arguments,2);f=function(){e.apply(this,h)}}return d(f,g)};c[b][We(a,!1)]=d}Ue.prototype.G=function(){var a=w.window;var b=a.setTimeout;b=b[We(this,!1)]||b;a.setTimeout=b;b=a.setInterval;b=b[We(this,!1)]||b;a.setInterval=b;Ue.J.G.call(this)};
function Ye(a){B.call(this,"Error in protected function: "+(a&&a.message?String(a.message):String(a)),a);(a=a&&a.stack)&&"string"===typeof a&&(this.stack=a)}A(Ye,B);function $e(a,b,c){O.call(this);this.m=b||null;this.j={};this.v=af;this.u=a;if(!c)if(this.g=null,$a&&!kb("10"))kc(x(this.h,this));else{this.g=new Ue(x(this.h,this));Ze(this.g,"setTimeout");Ze(this.g,"setInterval");a=this.g;b=w.window;c=["requestAnimationFrame","mozRequestAnimationFrame","webkitAnimationFrame","msRequestAnimationFrame"];for(var d=0;d<c.length;d++){var e=c[d];c[d]in b&&Ze(a,e)}a=this.g;vc=!0;b=x(a.g,a);for(c=0;c<tc.length;c++)tc[c](b);uc.push(a)}}A($e,O);
function bf(a){M.call(this,"a");this.error=a}A(bf,M);function af(a,b,c,d){if(d instanceof Map){var e={};d=r(d);for(var g=d.next();!g.done;g=d.next()){var f=r(g.value);g=f.next().value;f=f.next().value;e[g]=f}}else e=d;Md(a,null,b,c,e)}
$e.prototype.h=function(a,b){a=a.error||a;b=b?nb(b):{};a instanceof Error&&pb(b,a.__closure__error__context__984382||{});var c=lc(a);if(this.m)try{this.m(c,b)}catch(m){}var d=c.message.substring(0,1900);if(!(a instanceof B)||a.g){a=c.stack;try{var e=Hd(this.u,"script",c.fileName,"error",d,"line",c.lineNumber);a:{for(var g in this.j){var f=!1;break a}f=!0}if(!f){f=e;var h=Gd(this.j);e=Dd(f,h)}h={};h.trace=a;if(b)for(var k in b)h["context."+k]=b[k];var l=Gd(h);this.v(e,"POST",l,this.B)}catch(m){}}try{P(this,
new bf(c,b))}catch(m){}};$e.prototype.G=function(){var a=this.g;a&&"function"==typeof a.X&&a.X();$e.J.G.call(this)};function X(a,b,c,d,e,g){var f=new $e("//www.google.com/tools/feedback/jserror",void 0,!0);this.j=x(f.h,f);this.v=a;this.C=c||"en";this.B=b||!1;this.D=!!d;this.u=e;this.h=this.g=null;this.s=g}
function cf(a,b,c,d,e,g){if(df())return null;window.top.GOOGLE_HELP_CHAT_OPERATOR_V2=Te;if(window.top.GOOGLE_HELP_CHAT_SUPPORT)return null;a=new X(a,b,c,d,e,g);window.top.GOOGLE_HELP_CHAT_SUPPORT=a;ef(a);window.addEventListener("message",function(f){"helpPanelEnsureSubscribed"===f.data&&ff.test(f.origin)&&(window.top.GOOGLE_HELP_CHAT_SUPPORT.S(),console.log("Chat ensureSubscribed called by HP event listener."))});return a}
function df(){var a=window;try{return null==a||null==a.top||null==a.top.document}catch(b){return!0}}function ef(a){var b={helpCenterName:a.v,localeName:a.C,source:1,rosterId:"roster-for-Google-Help",isRtl:a.B,alphaTestMode:!1,stagingMode:a.D,timeoutMs:2E4,authUser:a.u,apiKey:a.s},c=zb("DIV",{id:"roster-for-Google-Help",style:"display: none"});window.top.document.body.appendChild(c);try{a.i=new Te(b)}catch(d){a.j(d)}}function gf(a,b,c){if(null!=b&&null!=c){var d={};d[b]=c;T(Pe(a.i,d),a.j)}}n=X.prototype;
n.fa=function(a){this.g=a;gf(this,this.g,this.l)};n.ga=function(a){this.h=a;gf(this,this.h,this.m)};n.ya=function(a){this.l=a;gf(this,this.g,this.l)};n.za=function(a){this.m=a;gf(this,this.h,this.m)};n.ma=function(a){null!=this.g&&T(Re(this.i,this.g,a),this.j)};n.xa=function(a){null!=this.h&&T(Re(this.i,this.h,a),this.j)};n.ba=function(){null==this.g&&null==this.h||T(Qe(this.i),this.j)};n.S=function(){this.i.S()};var ff=new RegExp(/^https:\/\/(pay.*|billing-ads-qa-devel|daily-1|dasher-workspace-*|meet-dev|gpay-landing.*|spot.*|tokenized.*)?\.?(bpui0|developers|corp|meet|payments|pay|play|sandbox|workspace)\.(google|youtube|admob)\.\w+\.?\w*/);
X.prototype.setChatPool=X.prototype.fa;X.prototype.setHangoutPool=X.prototype.ga;X.prototype.setChatCallback=X.prototype.ya;X.prototype.setHangoutCallback=X.prototype.za;X.prototype.requestChatSupport=X.prototype.ma;X.prototype.requestHangoutSupport=X.prototype.xa;X.prototype.getAvailabilities=X.prototype.ba;X.prototype.ensureSubscribed=X.prototype.S;function hf(){}hf.prototype.next=function(){return jf};var jf={done:!0,value:void 0};hf.prototype.M=function(){return this};function kf(a){if(a instanceof Y||a instanceof lf||a instanceof Z)return a;if("function"==typeof a.next)return new Y(function(){return a});if("function"==typeof a[Symbol.iterator])return new Y(function(){return a[Symbol.iterator]()});if("function"==typeof a.M)return new Y(function(){return a.M()});throw Error("Not an iterator or iterable.");}function Y(a){this.g=a}Y.prototype.M=function(){return new lf(this.g())};Y.prototype[Symbol.iterator]=function(){return new Z(this.g())};Y.prototype.h=function(){return new Z(this.g())};
function lf(a){this.g=a}v(lf,hf);lf.prototype.next=function(){return this.g.next()};lf.prototype[Symbol.iterator]=function(){return new Z(this.g)};lf.prototype.h=function(){return new Z(this.g)};function Z(a){Y.call(this,function(){return a});this.i=a}v(Z,Y);Z.prototype.next=function(){return this.i.next()};function mf(){};function nf(){}A(nf,mf);nf.prototype[Symbol.iterator]=function(){return kf(this.M(!0)).h()};function of(a){this.g=a}A(of,nf);of.prototype.set=function(a,b){try{this.g.setItem(a,b)}catch(c){if(0==this.g.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};of.prototype.get=function(a){a=this.g.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};function pf(a){a.g.removeItem("GOOGLE_HELP_SESSION_STATE")}
of.prototype.M=function(a){var b=0,c=this.g,d=new hf;d.next=function(){if(b>=c.length)return jf;var e=c.key(b++);if(a)return{value:e,done:!1};e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return{value:e,done:!1}};return d};of.prototype.key=function(a){return this.g.key(a)};function qf(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.g=a}A(qf,of);function rf(){L.call(this);this.g=new qf}v(rf,L);(function(a){var b=a.helpCenterPath,c=a.locale,d=a.authuser,e=a.escalationJSONString,g=!!a.useStagingServer;a=a.apiKey;var f=document.body;a:{var h=9==f.nodeType?f:f.ownerDocument||f.document;if(h.defaultView&&h.defaultView.getComputedStyle&&(h=h.defaultView.getComputedStyle(f,null))){h=h.direction||h.getPropertyValue("direction")||"";break a}h=""}b=cf(b,"rtl"==(h||(f.currentStyle?f.currentStyle.direction:null)||f.style&&f.style.direction),c,g,d,a);c=new rf;e&&(pf(c.g),e={oa:JSON.parse(e).oa},e.sessionTimestamp=
(new Date).getTime(),c.g.set("GOOGLE_HELP_SESSION_STATE",JSON.stringify(e)));if(e=c.g.get("GOOGLE_HELP_SESSION_STATE")){if(e=JSON.parse(e),d=(new Date).getTime(),g=e.sessionTimestamp,!g||"number"!==typeof g||d>g+6E4)pf(c.g),e=null}else e=null;c=(e||{}).escalationOptions;b&&c&&(e=c.hangout||{},(c=(c.chat||{}).chat_pool_id)&&b.fa(c),(e=e.hangout_pool_id)&&b.ga(e),b.ba())}).apply(w,w.GOOGLE_HELP_CHAT_ARGUMENTS);}).call(this);
